version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app # 코드 변경 -> 자동 reload
    env_file: ./backend/.env
    environment:
      IN_DOCKER: 'true'
      NEO4J_URI: 'bolt://neo4j:7687'
      OLLAMA_API_URL: 'http://ollama:11434'
    ports:
      - '8000:8000'
    depends_on: [neo4j, ollama]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    ports:
      - '5173:5173'
    depends_on: [backend]

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_dbms_security_auth__enabled: 'false'
    volumes: [neo4j_data:/data]
    ports:
      - '7474:7474'
      - '7687:7687'

  ollama:
    image: ollama/ollama:latest
    volumes: [ollama_models:/root/.ollama]
    ports:
      - '11434:11434'

volumes:
  neo4j_data:
  ollama_models:
  frontend_node_modules:
